"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import type { FakeAnalysisResult } from "@/lib/fakeAnalysis";
import ScoreMeter from "@/components/ScoreMeter";
import AnalysisList from "@/components/AnalysisList";

type Props = {
  imageDataUrl: string;
  result: FakeAnalysisResult;
};

function confidenceFromScore(score: number) {
  // For demo purposes, confidence tracks score but stays realistic.
  const jitter = (Math.random() - 0.5) * 8;
  return Math.max(45, Math.min(96, Math.round(score * 0.82 + 18 + jitter)));
}

export default function ResultCard({ imageDataUrl, result }: Props) {
  const confidence = confidenceFromScore(result.authenticity_score);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.55 }}
      className="glass overflow-hidden rounded-2xl"
    >
      <div className="grid gap-0 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="relative">
          <div className="relative aspect-[16/11]">
            <Image
              src={imageDataUrl}
              alt="Uploaded product"
              fill
              className="object-cover"
              unoptimized
              priority
            />
          </div>
          <div className="absolute inset-0 bg-gradient-to-tr from-black/45 via-transparent to-black/10" />

          <div className="absolute left-5 top-5">
            <div className="rounded-full bg-white/8 px-3 py-1 text-[11px] font-semibold text-white/80 ring-1 ring-white/15">
              {result.product_name}
            </div>
          </div>

          <div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-black/30 p-4 ring-1 ring-white/10 backdrop-blur">
            <div className="flex items-center justify-between text-[11px] text-white/55">
              <span>Confidence meter</span>
              <span>{confidence}%</span>
            </div>
            <div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10">
              <div
                className="h-full rounded-full bg-gradient-to-r from-white/20 via-white/40 to-white/20"
                style={{ width: `${confidence}%` }}
              />
            </div>
          </div>
        </div>

        <div className="p-6">
          <div className="space-y-5">
            <ScoreMeter
              score={result.authenticity_score}
              status={result.status}
            />
            <AnalysisList items={result.analysis} />

            <div className="rounded-2xl bg-white/5 p-5 ring-1 ring-white/10">
              <div className="text-[11px] font-semibold tracking-wide text-white/55">
                NOTES
              </div>
              <div className="mt-2 text-xs leading-relaxed text-white/65">
                This report is generated by simulated client-side logic for demo
                UI purposes. No real verification, manufacturer references, or
                barcode databases are used.
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

